#!/bin/bash

# 간단한 사용 가이드

echo "=========================================="
echo "🐳 SAM + CLIP Docker Training"
echo "=========================================="
echo ""
echo "📋 Quick Commands:"
echo ""
echo "1️⃣  Build Docker image:"
echo "   ./docker-build.sh"
echo ""
echo "2️⃣  Test environment:"
echo "   ./docker-test.sh"
echo ""
echo "3️⃣  Start training:"
echo "   ./docker-train.sh"
echo ""
echo "4️⃣  Interactive mode:"
echo "   ./docker-run.sh"
echo ""
echo "5️⃣  Start TensorBoard:"
echo "   ./docker-tensorboard.sh"
echo ""
echo "6️⃣  View logs:"
echo "   docker logs -f sam-clip-train"
echo ""
echo "7️⃣  Stop containers:"
echo "   docker stop sam-clip-train"
echo "   docker stop sam-clip-tensorboard"
echo ""
echo "=========================================="
echo "📚 For detailed documentation:"
echo "   - Docker: DOCKER_GUIDE.md"
echo "   - Project: PROJECT_GUIDE.md"
echo "   - General: README.md"
echo "=========================================="
